### ISSUE TITLE
Extension load issue

### ISSUE THREAD

**Issue by zukko78** [newrelic-experimental/newrelic-java-osb-12#3]
[NOTE]: Extension load issue

## Expected Behavior

Load all *jar

## Relevant Logs / Console output

Oracle OSB server based on weblogic 12c

[oracle@test-server-domain1-osb-server16 oracle]$ ls -ls /u01/newrelic/
total 20012
    0 drwxr-xr-x. 2 oracle oracle      235 Nov 15 17:55 extensions
    0 drwxr-x---. 2 oracle oracle       32 Dec  7 21:08 logs
20012 -rw-r--r--. 1 oracle oracle 20490624 Nov 15 17:55 newrelic.jar
[oracle@test-server-domain1-osb-server16 oracle]$ ls -ls /u01/newrelic/extensions/
total 40
4 -rw-r--r--. 1 oracle oracle 655 Nov 15 17:55 osb-adapters.jar
4 -rw-r--r--. 1 oracle oracle 654 Nov 15 17:55 osb-context.jar
4 -rw-r--r--. 1 oracle oracle 625 Nov 15 17:55 osb-http-12.2.jar
4 -rw-r--r--. 1 oracle oracle 619 Nov 15 17:55 osb-jca.jar
4 -rw-r--r--. 1 oracle oracle 650 Nov 15 17:55 osb-jms.jar
4 -rw-r--r--. 1 oracle oracle 650 Nov 15 17:55 osb-mdb.jar
4 -rw-r--r--. 1 oracle oracle 649 Nov 15 17:55 osb-mq.jar
4 -rw-r--r--. 1 oracle oracle 660 Nov 15 17:55 osb-pipeline-12.2.jar
4 -rw-r--r--. 1 oracle oracle 653 Nov 15 17:55 osb-poller.jar
4 -rw-r--r--. 1 oracle oracle 662 Nov 15 17:55 osb-transports-12.2.jar

## Additional context

2021-12-07T21:08:53,004+0000 [1497 1] com.newrelic INFO: Writing to New Relic log file: /u01/newrelic/logs/newrelic_agent.log
2021-12-07T21:08:53,005+0000 [1497 1] com.newrelic INFO: JRE vendor Oracle Corporation version 1.8.0_311
2021-12-07T21:08:53,005+0000 [1497 1] com.newrelic INFO: JVM vendor Oracle Corporation Java HotSpot(TM) 64-Bit Server VM version 25.311-b25
2021-12-07T21:08:53,006+0000 [1497 1] com.newrelic INFO: OS Linux version 3.10.0-1160.42.2.el7.x86_64 arch amd64
2021-12-07T21:08:53,007+0000 [1497 1] com.newrelic INFO: Agent Host: test-server-domain1-osb-server16 IP: 10.233.73.188
2021-12-07T21:08:53,007+0000 [1497 1] com.newrelic INFO: New Relic Agent v7.1.1 is initializing...
2021-12-07T21:08:55,217+0000 [1497 1] com.newrelic ERROR: Unable to load extension osb-adapters.jar
2021-12-07T21:08:55,217+0000 [1497 1] com.newrelic ERROR: Unable to load extension osb-context.jar
2021-12-07T21:08:55,218+0000 [1497 1] com.newrelic ERROR: Unable to load extension osb-http-12.2.jar
2021-12-07T21:08:55,218+0000 [1497 1] com.newrelic ERROR: Unable to load extension osb-jca.jar
2021-12-07T21:08:55,219+0000 [1497 1] com.newrelic ERROR: Unable to load extension osb-jms.jar
2021-12-07T21:08:55,220+0000 [1497 1] com.newrelic ERROR: Unable to load extension osb-mdb.jar
2021-12-07T21:08:55,220+0000 [1497 1] com.newrelic ERROR: Unable to load extension osb-mq.jar
2021-12-07T21:08:55,221+0000 [1497 1] com.newrelic ERROR: Unable to load extension osb-pipeline-12.2.jar
2021-12-07T21:08:55,221+0000 [1497 1] com.newrelic ERROR: Unable to load extension osb-poller.jar
2021-12-07T21:08:55,222+0000 [1497 1] com.newrelic ERROR: Unable to load extension osb-transports-12.2.jar
2021-12-07T21:08:56,867+0000 [1497 10] com.newrelic INFO: Instrumentation com.newrelic.instrumentation.jdbc-resultset is disabled. Skipping.
2021-12-07T21:09:10,811+0000 [1497 1] com.newrelic.agent.RPMServiceManagerImpl INFO: Configured to connect to New Relic at collector.newrelic.com:443
2021-12-07T21:09:15,707+0000 [1497 1] com.newrelic INFO: Setting audit_mode to false
2021-12-07T21:09:16,825+0000 [1497 1] com.newrelic INFO: New Relic Agent v7.1.1 has started
2021-12-07T21:09:16,825+0000 [1497 1] com.newrelic INFO: Agent class loader: com.newrelic.bootstrap.BootstrapAgent$JVMAgentClassLoader@799f10e

**Comment by dhilpipre** [comment]
This is not an issue with the extensions but rather with the agent reading the jar files.   It may be a permissions problem, ensure that the user id running OSB has read permissions on the jars.  Also setting the logging level to finer in newrelic.yml will print the exception that causes the error message

**Comment by zukko78** [comment]
Hi there, as I mentioned all permission were grunted for user Oracle, under it OSB run, error we got after download and put *.jar to extensions dir:

2022-06-17T22:07:50,302+0000 [1562 1] com.newrelic ERROR: Unable to load extension osb-adapters.jar
2022-06-17T22:07:50,302+0000 [1562 1] com.newrelic FINER: java.util.zip.ZipException: error in opening zip file
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_311]
        at java.util.zip.ZipFile.<init>(ZipFile.java:226) ~[?:1.8.0_311]
        at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_311]
        at java.util.jar.JarFile.<init>(JarFile.java:170) ~[?:1.8.0_311]
        at java.util.jar.JarFile.<init>(JarFile.java:134) ~[?:1.8.0_311]
        at com.newrelic.agent.extension.JarExtension.create(JarExtension.java:71) ~[newrelic.jar:7.1.1]
        at com.newrelic.agent.extension.ExtensionService.loadJars(ExtensionService.java:474) [newrelic.jar:7.1.1]
        at com.newrelic.agent.extension.ExtensionService.loadJarExtensions(ExtensionService.java:463) [newrelic.jar:7.1.1]
        at com.newrelic.agent.extension.ExtensionService.loadExtensionJars(ExtensionService.java:195) [newrelic.jar:7.1.1]
        at com.newrelic.agent.extension.ExtensionService.doStart(ExtensionService.java:106) [newrelic.jar:7.1.1]
        at com.newrelic.agent.service.AbstractService.start(AbstractService.java:63) [newrelic.jar:7.1.1]
        at com.newrelic.agent.service.ServiceManagerImpl.doStart(ServiceManagerImpl.java:189) [newrelic.jar:7.1.1]
        at com.newrelic.agent.service.AbstractService.start(AbstractService.java:63) [newrelic.jar:7.1.1]
        at com.newrelic.agent.Agent.continuePremain(Agent.java:162) [newrelic.jar:7.1.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_311]
        at com.newrelic.bootstrap.BootstrapAgent.startAgent(BootstrapAgent.java:178) [newrelic.jar:7.1.1]
        at com.newrelic.bootstrap.BootstrapAgent.premain(BootstrapAgent.java:116) [newrelic.jar:7.1.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_311]
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386) [?:1.8.0_311]
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401) [?:1.8.0_311]
2022-06-17T22:07:50,303+0000 [1562 1] com.newrelic ERROR: Unable to load extension osb-context.jar
2022-06-17T22:07:50,304+0000 [1562 1] com.newrelic FINER: java.util.zip.ZipException: error in opening zip file
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_311]
        at java.util.zip.ZipFile.<init>(ZipFile.java:226) ~[?:1.8.0_311]
        at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_311]

**Comment by zukko78** [comment]
java -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b25, mixed mode)

**Comment by zukko78** [comment]
found the main issue. We can close this request

**Comment by zukko78** [comment]
found the main issue.
